modLoader="javafml"
loaderVersion="${forgelike_loader_ver}"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mixins]]
config = "mixins.${id}.json"
[[mixins]]
config = "mixins.${id}.neo.json"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
logoFile="${icon}"
authors="${authors}"
description='''
${description}
'''

${depends}

